language: ruby
script: bundle exec appraisal rake
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.13.0
before_install:
  - gem install bundler
before_script:
  - bundle exec appraisal install
  - ./bin/literals
env:
  - DATABASE=postgres
  - DATABASE=mysql
  - DATABASE=sqlite
