language: ruby
script: bundle exec appraisal rspec
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.10.0
before_install:
  - gem install bundler
before_script:
  - bundle exec appraisal install
  - ./bin/literals
env:
  - DATABASE=postgres
  - DATABASE=mysql
  - DATABASE=sqlite
